import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Image from "next/image";
import landingImage from "../../public/wafflecream.png";
import waffles from "../../public/waffles.png";

export default function Home() {
  const router = useRouter();

  return (
    <div className="h-screen bg-gradient-to-r from-[#3b4260] to-[#401e3c]">
      <Head>
        <title>WaffleSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-between">
        <div
          className="mt-5 ml-5 cursor-pointer flex items-center"
          onClick={() => router.push("/")}
        >
          <Image src={waffles} alt="Logo" width="50" height="50" />{" "}
          <span className="font-bold text-white text-xl">WaffleSwap</span>
        </div>
      </div>

      <div className="md:container md:w-4/5 md:mt-[30vh] m-10 text-white flex justify-between gap-5">
        <div className="space-y-4">
          <div className="text-6xl font-bold">
            A Decentralized Exchange on Ethereum.
          </div>
          <div className="text-2xl">
            WaffleSwap is a decentralized exchange on Ethereum built for
            performance and simplicity.
          </div>
          <button
            type="button"
            className={`h-14 w-48 px-4 py-2 border border-transparent font-bold text-xl text-center rounded-2xl text-purple-900 bg-purple-500 hover:bg-purple-700 hover:text-purple-300 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-opacity-50 transition ease-in-out duration-200`}
            onClick={() => {
              router.push("/swap");
            }}
          >
            Enter App
          </button>
        </div>

        <div className="w-[300px]">
          <Image src={landingImage} alt="Hero Image" width="400" height="400" />
        </div>
      </div>
    </div>
  );
}
