import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="h-screen bg-gradient-to-r from-[#3b4260] to-[#401e3c]">
      <Head>
        <title>WaffleSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-2xl text-white-100">Landing Page</h1>
      <Link href="/swap">Enter App</Link>
    </div>
  );
}
