import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import ethereum from "../../public/ethereum.png";
import waffles from "../../public/waffles.png";
import {
  Button,
  BuySellSwitch,
  Label,
  TokenBox,
  FullButton,
} from "../components/ui";

const buyQuotes = [
  ["Get Your Waffle", "🧇"],
  ["Eat Your Waffle", "🍽️"],
  ["Waffle Goes In", "↙️"],
  ["Come On! Let's Pump Some Waffle", "💪"],
];
const sellQuotes = [
  ["Get Your Ethereum", "🪙"],
  ["Dump Your Waffle", "🤮"],
  ["Waffle Goes Out", "↗️"],
  ["Hate to see you dump waffle", "😿"],
];

const BuyForm = () => {
  let idx = Math.floor(Math.random() * buyQuotes.length);
  return (
    <div>
      <TokenBox logo={ethereum} ticker="ETH" alt="eth logo" />
      <TokenBox logo={waffles} ticker="WFL" alt="wfl logo" disabled={true} />
      <div className="float-right">
        <Label>1 ETH = 100 WFL</Label>
      </div>
      <FullButton emoji={buyQuotes[idx][1]}>{buyQuotes[idx][0]}</FullButton>
    </div>
  );
};

const SellForm = () => {
  let idx = Math.floor(Math.random() * sellQuotes.length);
  return (
    <div>
      <TokenBox logo={waffles} ticker="WFL" alt="wfl logo" />
      <TokenBox logo={ethereum} ticker="ETH" alt="eth logo" disabled={true} />
      <div className="float-right">
        <Label>1 WFL = 0.001 ETH</Label>
      </div>
      <FullButton emoji={sellQuotes[idx][1]}>{sellQuotes[idx][0]}</FullButton>
    </div>
  );
};

export default function Exchange() {
  const [state, setState] = useState("buy");
  return (
    <div>
      <Head>
        <title>WaffleSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:container md:w-2/5 space-y-4 mt-40 mb-10 mx-4">
        <BuySellSwitch state={state} setState={setState}>
          Buy
        </BuySellSwitch>
        <div className="w-xl p-6 text-left rounded-3xl shadow-lg backdrop-blur-3xl bg-white/50">
          {state == "buy" ? <BuyForm /> : <SellForm />}
        </div>
      </div>
    </div>
  );
}
